packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - globals@17.11.0
overrides:
  esbuild: 0.21.5
  tsx: 4.16.2
